version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./django-api:/django-api
    command: >
      sh -c "python ./tutorial/manage.py migrate &&
             python ./tutorial/manage.py runserver 0.0.0.0:8000"
